Repository hybridapp-io/ham-deployable-operator, pull requests merged in 2020-06, with the labels that each got.

#15 remove bou.ke/monkey
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#17 add placement target for deployer
  deploy/crds/core.hybridapp.io_deployers_crd.yaml
  deploy/crds/core.hybridapp.io_deployersets_crd.yaml
  pkg/apis/core/v1alpha1/deployer_types.go
Labels: approved, lgtm, size/M

#18 template inherits namespace from hdpl
  pkg/controller/deployable/hybriddeployable_template.go
  pkg/controller/deployable/hybriddeployable_template_test.go
Labels: approved, lgtm, size/L

#20 Output and dependency model unit test coverage
  pkg/apis/core/v1alpha1/deployable_types.go
  pkg/controller/deployable/hybriddeployable_controller.go
  pkg/controller/deployable/hybriddeployable_controller_test.go
  pkg/controller/deployable/hybriddeployable_dependencies_test.go
  pkg/controller/deployable/hybriddeployable_status.go
  pkg/controller/deployable/hybriddeployable_status_test.go
  pkg/controller/deployable/hybriddeployable_template.go
Labels: approved, lgtm, size/L
