Repository hybridapp-io/ham-deployable-operator, pull requests merged in 2020-07, with the labels that each got.

#21 update addMetrics and serveCRMetrics
  cmd/operator/operator.go
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#22 replace cluster registry with object reference
  pkg/apis/apis.go
  pkg/controller/deployable/hybriddeployable_placement.go
Labels: approved, lgtm, size/S

#23 deployer scope
  deploy/crds/core.hybridapp.io_deployers_crd.yaml
  deploy/crds/core.hybridapp.io_deployersets_crd.yaml
  go.mod
  pkg/apis/core/v1alpha1/deployer_types.go
  pkg/controller/deployable/hybriddeployable_dependencies_test.go
  pkg/controller/deployable/hybriddeployable_status_test.go
  pkg/controller/deployable/hybriddeployable_template.go
  pkg/controller/deployable/hybriddeployable_template_test.go
  pkg/utils/deployer_utils.go
Labels: approved, lgtm, size/XL

#24 hdpl namespace propagation
  pkg/controller/deployable/hybriddeployable_controller_test.go
  pkg/controller/deployable/hybriddeployable_template.go
Labels: approved, lgtm, size/XS

#25 Updated owners list
  OWNERS
Labels: approved, lgtm, size/XS

#27 Release 0.0.1
  Makefile
  README.md
Labels: approved, lgtm, size/XS
