Repository hybridapp-io/ham-deployable-operator, pull requests merged in 2020-08, with the labels that each got.

#28 new version of go-client
  go.mod
  go.sum
  pkg/controller/deployable/hybriddeployable_controller_test.go
  pkg/controller/deployable/hybriddeployable_dependencies.go
  pkg/controller/deployable/hybriddeployable_dependencies_test.go
  pkg/controller/deployable/hybriddeployable_placement.go
  pkg/controller/deployable/hybriddeployable_registry.go
  pkg/controller/deployable/hybriddeployable_status_test.go
  pkg/controller/deployable/hybriddeployable_template.go
  pkg/controller/deployable/hybriddeployable_template_test.go
Labels: approved, lgtm, size/L

#29 handle ignored resources during registry init
  pkg/controller/deployable/hybriddeployable_controller.go
  pkg/controller/deployable/hybriddeployable_registry.go
  pkg/controller/deployable/hybriddeployable_registry_test.go
  pkg/controller/deployable/hybriddeployable_status.go
  pkg/controller/deployable/hybriddeployable_template.go
Labels: approved, lgtm, size/L

#31 handle ignored resources during registry init
  pkg/controller/deployable/hybriddeployable_controller.go
  pkg/controller/deployable/hybriddeployable_registry.go
  pkg/controller/deployable/hybriddeployable_registry_test.go
  pkg/controller/deployable/hybriddeployable_status.go
  pkg/controller/deployable/hybriddeployable_template.go
Labels: approved, lgtm, size/L

#32 Update Dockerfile
  build/Dockerfile
Labels: approved, lgtm, size/XS

#33 lastUpdateTime refreshed only when status changes
  pkg/controller/deployable/hybriddeployable_controller_test.go
  pkg/controller/deployable/hybriddeployable_status.go
  pkg/controller/deployable/hybriddeployable_status_test.go
Labels: approved, lgtm, size/M

#34 reload status
  pkg/controller/deployable/hybriddeployable_dependencies_test.go
  pkg/controller/deployable/hybriddeployable_status.go
  pkg/controller/deployable/hybriddeployable_status_test.go
  pkg/controller/deployable/hybriddeployable_template_test.go
Labels: approved, lgtm, size/L
