Repository hybridapp-io/ham-deployable-operator, pull requests merged in 2020-05, with the labels that each got.

#3 Sdk017
  README.md
  common/scripts/install-operator-sdk.sh
  go.mod
  go.sum
Labels: approved, lgtm, size/XL

#4 Hdpl labels
  .gitignore
  pkg/apis/core/v1alpha1/deployable_types.go
  pkg/controller/deployable/hybriddeployable_controller_test.go
  pkg/controller/deployable/hybriddeployable_placement.go
  pkg/controller/deployable/hybriddeployable_template.go
Labels: approved, lgtm, size/L

#5 Revert "Hdpl labels"
  .gitignore
  pkg/apis/core/v1alpha1/deployable_types.go
  pkg/controller/deployable/hybriddeployable_controller_test.go
  pkg/controller/deployable/hybriddeployable_placement.go
  pkg/controller/deployable/hybriddeployable_template.go
Labels: approved, lgtm, size/L

#6 additional checking during object upgrade
  pkg/controller/deployable/hybriddeployable_placement.go
  pkg/controller/deployable/hybriddeployable_template.go
Labels: approved, lgtm, size/S

#7 Update Dockerfile
  build/Dockerfile
Labels: approved, lgtm, size/S

#9 Doc
  README.md
  deploy/crds/core.hybridapp.io_v1alpha1_deployable_cr.yaml
  deploy/crds/core.hybridapp.io_v1alpha1_deployerset_cr.yaml
  examples/simple/simple_deployable_cr.yaml
  examples/simple/simple_deployer_cr.yaml
Labels: approved, lgtm, size/M

#10 Update Dockerfile
  build/Dockerfile
Labels: approved, lgtm, size/XS

#12 fix false alarm in sql string check
  pkg/controller/deployable/hybriddeployable_controller.go
  pkg/controller/deployable/hybriddeployable_template.go
  pkg/controller/deployable/hybriddeployable_template_test.go
Labels: approved, lgtm, size/S

#13 fixed discovery annotations
  pkg/apis/core/v1alpha1/deployer_types.go
Labels: approved, lgtm, size/XS

#14 added list of ignored active GVRs
  pkg/controller/deployable/hybriddeployable_registry.go
  pkg/controller/deployable/hybriddeployable_template.go
Labels: approved, lgtm, size/M
