Repository hybridapp-io/ham-deployable-operator, pull requests merged in 2021-04, with the labels that each got.

#48 Comments
  pkg/controller/deployable/hybriddeployable_controller.go
Labels: approved, lgtm, size/XS

#49 Fix status not updating on HDPL
  pkg/controller/deployable/hybriddeployable_controller.go
  pkg/controller/deployable/hybriddeployable_status.go
  pkg/controller/deployable/hybriddeployable_status_test.go
Labels: approved, lgtm, size/L

#50 Cluster scoped resources
  pkg/apis/core/v1alpha1/deployable_types.go
  pkg/controller/deployable/hybriddeployable_template.go
  pkg/utils/deployer_utils.go
Labels: approved, lgtm, size/S

#51 Placement decision
  pkg/controller/deployable/hybriddeployable_placement.go
Labels: approved, lgtm, size/XS
