Repository hybridapp-io/ham-deployable-operator, pull requests merged in 2022-10, with the labels that each got.

#64 Replaced RHACM deployables with manifest works
  go.mod
  go.sum
  hack/test/apps.open-cluster-management.io_deployables_crd.yaml
  hack/test/apps.open-cluster-management.io_placementrules_crd.yaml
  hack/test/work.open-cluster-management.io_manifestworks_crd.yaml
  pkg/apis/apis.go
  pkg/apis/core/v1alpha1/deployable_types.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/deployable/hybriddeployable_controller.go
  pkg/controller/deployable/hybriddeployable_controller_test.go
  pkg/controller/deployable/hybriddeployable_dependencies.go
  pkg/controller/deployable/hybriddeployable_dependencies_test.go
  pkg/controller/deployable/hybriddeployable_registry.go
  pkg/controller/deployable/hybriddeployable_status.go
  pkg/controller/deployable/hybriddeployable_status_test.go
  pkg/controller/deployable/hybriddeployable_suite_test.go
  pkg/controller/deployable/hybriddeployable_template.go
  pkg/controller/deployable/hybriddeployable_template_test.go
Labels: size/XXL, approved, lgtm

#65 Go update
  Makefile
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#67 update go modules
  go.mod
  go.sum
Labels: approved, lgtm, size/S
